- name: Deploy to Tomcat
  hosts: web
  become: yes
  tasks:
  - name: Copying WAR file to Tomcat
    copy:
      src: "/var/snap/jenkins/4874/workspace/AnsibleApp3/target/AnsibleApp3.war"
      dest: "/home/Thushar/tomcatNew/webapps/"
      remote_src: no
